--- !ditz.rubyforge.org,2008-03-06/project 
name: xyzzy.common-lisp
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: xyzzy.common-lisp
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.1"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2010-07-17 23:10:45.949405 Z
    - bowbow99 <bowbow99@gmail.com>
    - created
    - ""
