;;; -*- mode: lisp; package: common-lisp -*-
;;;
;;; cl.l --- Common Lisp compatibility layer for xyzzy.
;;;

(require "common-lisp/package")

(require "common-lisp/typespec+")
(require "common-lisp/typecase")

(require "common-lisp/print-unreadable-object")
(require "common-lisp/progv")

(require "common-lisp/setf-function-name")
(require "common-lisp/defun")

(require "common-lisp/pprint")
(provide "cl")

;;; cl.l ends here.
